### PR TITLE
futureminded updates

### PR DESCRIPTION
**Pull request by houseburger**
Added link to h3 tag for Mal Fletcher.
also added code to home.styl, however working with npm stylus didn’t
work, i don’t think i outputted it correctly. could u plz teach me how
to? thx!

### CODE REVIEW

**Comment by timothyachumba** [comment]
Just a note, branches should be descriptive of what they're for :) :dancer:

**Comment by timothyachumba** [comment]
@hauspa As for npm, you may need to run make install first and then make start. I will add the set up guide to the readme :)

**Comment by timothyachumba** [comment]
Also, I will merge one everything is done :)

**Comment by houseburger** [comment]
Haha ok yeah will choose a better name in the future ;)
Ok cool thanks! :)

**Pull request merged**
